"""
Base classes for feature engineering transformers.

This module provides the foundational classes for all feature engineering
transformers in the stock forecasting system.
"""

import pandas as pd
from abc import ABC, abstractmethod
from typing import List, Optional, Union
from sklearn.base import BaseEstimator, TransformerMixin
import logging

logger = logging.getLogger(__name__)


class BaseFeatureTransformer(BaseEstimator, TransformerMixin, ABC):
    """
    Abstract base class for all feature engineering transformers.
    
    This class provides a common interface for all feature transformers
    and ensures consistent behavior across different feature engineering methods.
    """
    
    def __init__(self, feature_prefix: str = ""):
        """
        Initialize the base feature transformer.
        
        Args:
            feature_prefix: Prefix to add to generated feature names
        """
        self.feature_prefix = feature_prefix
        self.feature_names_ = []
        self.is_fitted_ = False
        
    @abstractmethod
    def _transform(self, X: pd.DataFrame) -> pd.DataFrame:
        """
        Transform the input data.
        
        Args:
            X: Input DataFrame with time series data
            
        Returns:
            DataFrame with engineered features
        """
    
    def fit(self, X: pd.DataFrame, y: Optional[pd.Series] = None) -> 'BaseFeatureTransformer':
        """
        Fit the transformer to the data.
        
        Args:
            X: Input DataFrame with time series data
            y: Target values (optional, for supervised transformers)
            
        Returns:
            self: Fitted transformer
        """
        logger.info("Fitting %s", self.__class__.__name__)
        self._validate_input(X)
        self._fit(X, y)
        self.is_fitted_ = True
        return self
    
    def transform(self, X: pd.DataFrame) -> pd.DataFrame:
        """
        Transform the input data using fitted parameters.
        
        Args:
            X: Input DataFrame with time series data
            
        Returns:
            DataFrame with engineered features
        """
        if not self.is_fitted_:
            raise ValueError(f"{self.__class__.__name__} must be fitted before transform")
        
        self._validate_input(X)
        result = self._transform(X)
        
        # Add feature names if not already set
        if not hasattr(self, 'feature_names_') or not self.feature_names_:
            self.feature_names_ = list(result.columns)
        
        logger.info("Transformed data shape: %s", result.shape)
        return result
    
    def fit_transform(self, X: pd.DataFrame, y: Optional[pd.Series] = None) -> pd.DataFrame:
        """
        Fit the transformer and transform the data in one step.
        
        Args:
            X: Input DataFrame with time series data
            y: Target values (optional, for supervised transformers)
            
        Returns:
            DataFrame with engineered features
        """
        return self.fit(X, y).transform(X)
    
    def _fit(self, X: pd.DataFrame, y: Optional[pd.Series] = None) -> None:
        """
        Internal fit method to be implemented by subclasses.
        
        Args:
            X: Input DataFrame with time series data
            y: Target values (optional)
        """
    
    def _validate_input(self, X: pd.DataFrame) -> None:
        """
        Validate input data.
        
        Args:
            X: Input DataFrame to validate
            
        Raises:
            ValueError: If input data is invalid
        """
        if not isinstance(X, pd.DataFrame):
            raise ValueError("Input must be a pandas DataFrame")
        
        if X.empty:
            raise ValueError("Input DataFrame is empty")
        
        # Check for required columns (can be overridden by subclasses)
        self._validate_columns(X)
    
    def _validate_columns(self, X: pd.DataFrame) -> None:
        """
        Validate that required columns exist in the input data.
        Override this method in subclasses to specify required columns.
        
        Args:
            X: Input DataFrame to validate
            
        Raises:
            ValueError: If required columns are missing
        """
    
    def get_feature_names(self) -> List[str]:
        """
        Get the names of the features generated by this transformer.
        
        Returns:
            List of feature names
        """
        if not self.is_fitted_:
            raise ValueError(f"{self.__class__.__name__} must be fitted before getting feature names")
        return self.feature_names_.copy()
    
    def _create_feature_name(self, base_name: str) -> str:
        """
        Create a feature name with the appropriate prefix.
        
        Args:
            base_name: Base name for the feature
            
        Returns:
            Feature name with prefix
        """
        if self.feature_prefix:
            return f"{self.feature_prefix}_{base_name}"
        return base_name


class FeaturePipeline:
    """
    Pipeline for chaining multiple feature transformers.
    
    This class allows you to chain multiple feature engineering transformers
    together and apply them sequentially to the data.
    """
    
    def __init__(self, transformers: List[tuple]):
        """
        Initialize the feature pipeline.
        
        Args:
            transformers: List of (name, transformer) tuples
        """
        self.transformers = transformers
        self.named_transformers = dict(transformers)
        self.is_fitted_ = False
        
    def fit(self, X: pd.DataFrame, y: Optional[pd.Series] = None) -> 'FeaturePipeline':
        """
        Fit all transformers in the pipeline.
        
        Args:
            X: Input DataFrame with time series data
            y: Target values (optional)
            
        Returns:
            self: Fitted pipeline
        """
        logger.info("Fitting feature pipeline with %d transformers", len(self.transformers))
        
        current_X = X.copy()
        
        for name, transformer in self.transformers:
            logger.info("Fitting transformer: %s", name)
            current_X = transformer.fit_transform(current_X, y)
        
        self.is_fitted_ = True
        return self
    
    def transform(self, X: pd.DataFrame) -> pd.DataFrame:
        """
        Transform data using all fitted transformers.
        
        Args:
            X: Input DataFrame with time series data
            
        Returns:
            DataFrame with all engineered features
        """
        if not self.is_fitted_:
            raise ValueError("Pipeline must be fitted before transform")
        
        current_X = X.copy()
        
        for name, transformer in self.transformers:
            logger.info("Transforming with: %s", name)
            current_X = transformer.transform(current_X)
        
        return current_X
    
    def fit_transform(self, X: pd.DataFrame, y: Optional[pd.Series] = None) -> pd.DataFrame:
        """
        Fit all transformers and transform the data.
        
        Args:
            X: Input DataFrame with time series data
            y: Target values (optional)
            
        Returns:
            DataFrame with all engineered features
        """
        return self.fit(X, y).transform(X)
    
    def get_feature_names(self) -> List[str]:
        """
        Get all feature names from the pipeline.
        
        Returns:
            List of all feature names
        """
        if not self.is_fitted_:
            raise ValueError("Pipeline must be fitted before getting feature names")
        
        all_features = []
        for _, transformer in self.transformers:
            if hasattr(transformer, 'get_feature_names'):
                features = transformer.get_feature_names()
                all_features.extend(features)
        
        return all_features
    
    def get_transformer(self, name: str) -> BaseFeatureTransformer:
        """
        Get a specific transformer by name.
        
        Args:
            name: Name of the transformer
            
        Returns:
            The requested transformer
            
        Raises:
            KeyError: If transformer name not found
        """
        if name not in self.named_transformers:
            raise KeyError(f"Transformer '{name}' not found in pipeline")
        return self.named_transformers[name]
    
    def __len__(self) -> int:
        """Return the number of transformers in the pipeline."""
        return len(self.transformers)
    
    def __getitem__(self, index: Union[int, str]) -> BaseFeatureTransformer:
        """
        Get transformer by index or name.
        
        Args:
            index: Index (int) or name (str) of the transformer
            
        Returns:
            The requested transformer
        """
        if isinstance(index, int):
            return self.transformers[index][1]
        elif isinstance(index, str):
            return self.get_transformer(index)
        else:
            raise TypeError("Index must be int or str")
